import type { MetadataRoute } from "next";

import { brands } from "@/data/brands";
import { cmsPlatforms } from "@/data/cms-platforms";
import { industries } from "@/data/industries";
import { states } from "@/data/states";
import { wcagCriteria } from "@/data/wcag-criteria";

const baseUrl = "https://ratedwithai.com";

// Blog posts - add new posts here
const blogPosts = [
  "how-to-make-website-ada-compliant-2026",
  "accessibility-audit-checklist-2026",
  "accessibility-widgets",
  "ada-compliance-by-industry",
  "ada-compliance-checklist-2026",
  "ada-lawsuit-settlements-2026",
  "ada-title-ii-compliance-guide",
  "ada-title-ii-deadline-countdown-2026",
  "banking-accessibility-compliance",
  "best-website-accessibility-checker-tools-2026",
  "ecommerce-accessibility-guide",
  "european-accessibility-act-2025",
  "healthcare-accessibility-compliance",
  "how-to-check-website-ada-compliant",
  "how-to-fix-common-wcag-failures",
  "law-firm-accessibility-compliance",
  "small-business-accessibility-guide",
  "top-10-wcag-failures",
  "wcag-2-1-vs-2-2",
  "wcag-22-complete-guide",
  "website-accessibility-lawsuit-statistics-2026",
  "website-accessibility-testing-guide",
  "section-508-compliance-guide",
  "ada-lawsuit-reform-2026",
  "ada-website-compliance-guide",
  "wcag-compliance-guide",
  "accessibe-alternative",
  "accessibility-testing-services",
  "healthcare-website-accessibility-may-2026",
  "accessibe-review-2026",
  "accessibility-certification-guide",
  "siteimprove-alternative-2026",
  "web-accessibility-service",
  "audioeye-review-2026",
  "shopify-ada-compliance",
  "wordpress-accessibility-guide",
  "shopify-accessibility-apps",
  "ada-compliance-tool-comparison-2026",
  "best-ada-compliance-software",
  "ada-website-lawsuit-protection",
  "ada-website-compliance-deadline-2025-2026",
  "digital-accessibility-platform",
  "tabnav-alternative-2026",
  "accessibilitychecker-alternative-2026",
  "accessibe-pricing-2026",
  "ada-website-lawsuit-statistics-2026",
  "shopify-ada-compliance-guide-2026",
  "doj-ada-title-ii-rule-changes-2026",
  "higher-education-ada-compliance-2026",
  "accessibe-review",
  "best-accessibility-testing-tools",
  "wcag-22-checklist",
  "government-accessibility-compliance-cost-comparison-2026",
  "school-district-website-ada-compliance-2026",
  "nascio-state-ada-compliance-2025-report",
  "squarespace-ada-compliance-guide-2026",
  "fashion-nova-doj-settlement-rejected-2026",
  "utah-missouri-anti-ada-lawsuit-bills-2026",
  "irs-form-8826-disabled-access-credit-website-accessibility",
  "ada-lawsuits-ai-powered-pro-se-2025",
  "ada-website-lawsuit-costs-small-business-2026",
  "15000-ada-website-lawsuits-cox-media-investigation-2026",
  "ada-lawsuit-state-migration-2026",
  "california-sb-84-ada-right-to-cure-2026",
  "ftc-accessibe-fine-overlay-failures",
  "meta-ai-accessibility-fixes-axe-con-2026",
  "courts-fighting-back-serial-ada-website-plaintiffs",
  "axe-mcp-server-ai-accessibility-testing",
  "florida-ada-website-lawsuits-2026",
  "european-accessibility-act-eaa-compliance-us-businesses",
  "state-ada-reform-laws-tracker-2026",
  "vpat-accessibility-conformance-report-guide-2026",
  "ecommerce-accessibility-ada-compliance-guide",
  "repeat-ada-lawsuits-why-one-settlement-isnt-enough",
  "doj-wcag-not-ada-standard-2026",
  "mobile-app-accessibility-ada-compliance-guide-2026",
  "online-only-stores-ada-compliance-2026",
  "web-accessibility-trends-2026",
  "canada-accessible-canada-act-digital-accessibility-2027",
  "wcag-3-guide-2026",
  "university-website-accessibility-crisis-2026",
  "wix-ada-compliance-guide-2026",
  "ada-website-compliance-cost-2026",
  "how-to-respond-ada-website-lawsuit-demand-letter",
  "restaurant-website-ada-compliance-2026",
  "ada-compliance-audit-guide-2026",
  "pdf-accessibility-ada-compliance-guide-2026",
  "wordpress-accessibility-plugins-2026",
  "nonprofit-website-ada-compliance-guide-2026",
  "accessibility-statement-guide-template-2026",
  "alt-text-guide-how-to-write-image-accessibility",
  "gainesville-ada-lawsuits-small-business-lessons-2026",
  "iaap-accessibility-certification-guide-2026",
  "email-accessibility-guide-2026",
  "screen-reader-testing-guide-2026",
  "audioeye-pricing-2026",
  "accessible-website-examples-2026",
];

// Tool landing pages
const toolPages = [
  "ada-title-ii-compliance-checker",
  "accessibe-alternative",
  "accessibe-review",
  "free-accessibility-checker",
  "is-my-website-ada-compliant",
  "vpat-template",
  "accessibility-statement-generator",
  "color-contrast-checker",
  "pdf-accessibility-checker",
  "alt-text-generator",
  "userway-alternative",
  "wcag-compliance-tool",
  "ada-compliance-checker",
  "audioeye-alternative",
];

// Comparison pages
const comparePages = [
  "ratedwithai-vs-accessibe",
  "ratedwithai-vs-audioeye",
  "ratedwithai-vs-userway",
  "ratedwithai-vs-wave",
];

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    {
      url: baseUrl,
      changeFrequency: "weekly",
      priority: 1,
    },
    {
      url: `${baseUrl}/blog`,
      changeFrequency: "weekly",
      priority: 0.8,
      lastModified: new Date().toISOString(),
    },
    {
      url: `${baseUrl}/pricing`,
      changeFrequency: "monthly",
      priority: 0.6,
    },
    {
      url: `${baseUrl}/government`,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    ...toolPages.map((tool) => ({
      url: `${baseUrl}/tools/${tool}`,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    })),
    ...comparePages.map((page) => ({
      url: `${baseUrl}/compare/${page}`,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    })),
    ...blogPosts.map((post) => ({
      url: `${baseUrl}/blog/${post}`,
      changeFrequency: "monthly" as const,
      priority: 0.8,
      lastModified: new Date().toISOString(),
    })),
    ...brands.map((brand) => ({
      url: `${baseUrl}/check/${brand.slug}`,
      changeFrequency: "weekly" as const,
      priority: 0.7,
    })),
    ...wcagCriteria.map((criterion) => ({
      url: `${baseUrl}/wcag/${criterion.slug}`,
      changeFrequency: "monthly" as const,
      priority: 0.5,
    })),
    ...industries.map((industry) => ({
      url: `${baseUrl}/industry/${industry.slug}`,
      changeFrequency: "monthly" as const,
      priority: 0.6,
    })),
    ...cmsPlatforms.map((platform) => ({
      url: `${baseUrl}/cms/${platform.slug}`,
      changeFrequency: "monthly" as const,
      priority: 0.6,
    })),
    ...states.map((state) => ({
      url: `${baseUrl}/state/${state.slug}`,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    })),
  ];
}
